import 'package:http/http.dart' as http;
import 'dart:convert';

class Country {
  Future<List<dynamic>> getRate() async {
    var data3;
    final response =
        await http.get(Uri.parse("https://open.er-api.com/v6/latest/USD"));

    if (response.statusCode == 200) {
      data3 = jsonDecode(response.body.toString());
      return data3;
    } else {
      throw ("error");
    }
  }
  Future<dynamic> getInfo() async {
  var data;
  final response =
      await http.get(Uri.parse("https://restcountries.com/v3.1/all"));
  if (response.statusCode == 200) {
    data = jsonDecode(response.body);
    return data;
  } else {
    throw ("error");
  }
}

  Future<List<dynamic>> getCountryInfo() async {
    var data;
    final response = await http.get(Uri.parse(
        "https://gist.githubusercontent.com/amitjambusaria/b9adebcb4f256eae3dfa64dc9f1cc2ef/raw/6431d72439c8399b05d2b8e9d51153e5dee7ad3b/countries.json"));

    if (response.statusCode == 200) {
      data = jsonDecode(response.body.toString());
      return data;
    } else {
      throw ("error");
    }
  }

  Future<List<dynamic>> getCountryCurrecy() async {
    var data2;
    var response =
        await http.get(Uri.parse("https://open.er-api.com/v6/latest/USD"));
    if (response.statusCode == 200) {
      data2 = jsonDecode(response.body);
      return data2;
    } else {
      throw ("Error");
    }
  }

  Future<List<dynamic>> getCountryFlag() async {
    var data2;
    final response2 = await http.get(Uri.parse(
        "cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/index.json"));

    if (response2.statusCode == 200) {
      data2 = jsonDecode(response2.body.toString());
      return data2;
    } else {
      throw ("error");
    }
  }

  final countryList = [
    'AFGHANISTAN',
    'ALBANIA',
    'ALGERIA',
    'AMERICAN SAMOA',
    'ANDORRA',
    'ANGOLA',
    'ANGUILLA',
    'ANTARCTICA',
    'ANTIGUA AND BARBUDA',
    'ARGENTINA',
    'ARMENIA',
    'ARUBA',
    'AUSTRALIA',
    'AUSTRIA',
    'AZERBAIJAN',
    'BAHAMAS (THE)',
    'BAHRAIN',
    'BANGLADESH',
    'BARBADOS',
    'BELARUS',
    'BELGIUM',
    'BELIZE',
    'BENIN',
    'BERMUDA',
    'BHUTAN',
    'BOLIVIA (PLURINATIONAL STATE OF)',
    'BONAIRE, SINT EUSTATIUS AND SABA',
    'BOSNIA AND HERZEGOVINA',
    'BOTSWANA',
    'BOUVET ISLAND',
    'BRAZIL',
    'BRITISH INDIAN OCEAN TERRITORY (THE)',
    'BRUNEI DARUSSALAM',
    'BULGARIA',
    'BURKINA FASO',
    'BURUNDI',
    'CABO VERDE',
    'CAMBODIA',
    'CAMEROON',
    'CANADA',
    'CAYMAN ISLANDS (THE)',
    'CENTRAL AFRICAN REPUBLIC (THE)',
    'CHAD',
    'CHILE',
    'CHILE',
    'CHINA',
    'CHRISTMAS ISLAND',
    'COCOS (KEELING) ISLANDS (THE)',
    'COLOMBIA',
    'COMOROS (THE)',
    'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
    'CONGO (THE)',
    'COOK ISLANDS (THE)',
    'COSTA RICA',
    'CROATIA',
    'CUBA',
    'CUBA',
    'CURAÇAO',
    'CYPRUS',
    'CZECH REPUBLIC (THE)',
    "CÔTE D'IVOIRE",
    'DENMARK',
    'DJIBOUTI',
    'DOMINICA',
    'DOMINICAN REPUBLIC (THE)',
    'ECUADOR',
    'EGYPT',
    'EL SALVADOR',
    'EQUATORIAL GUINEA',
    'ERITREA',
    'ESTONIA',
    'ETHIOPIA',
    'EUROPEAN UNION',
    'FALKLAND ISLANDS (THE) [MALVINAS]',
    'FAROE ISLANDS (THE)',
    'FIJI',
    'FINLAND',
    'FRANCE',
    'FRENCH GUIANA',
    'FRENCH POLYNESIA',
    'FRENCH SOUTHERN TERRITORIES (THE)',
    'GABON',
    'GAMBIA (THE)',
    'GEORGIA',
    'GERMANY',
    'GHANA',
    'GIBRALTAR',
    'GREECE',
    'GREENLAND',
    'GRENADA',
    'GUADELOUPE',
    'GUAM',
    'GUATEMALA',
    'GUERNSEY',
    'GUINEA',
    'GUINEA-BISSAU',
    'GUYANA',
    'HAITI',
    'HEARD ISLAND AND McDONALD ISLANDS',
    'HOLY SEE (THE)',
    'HONDURAS',
    'HONG KONG',
    'HUNGARY',
    'ICELAND',
    'INDIA',
    'INDONESIA',
    'INTERNATIONAL MONETARY FUND (IMF)',
    'IRAN (ISLAMIC REPUBLIC OF)',
    'IRAQ',
    'IRELAND',
    'ISLE OF MAN',
    'ISRAEL',
    'ITALY',
    'JAMAICA',
    'JAPAN',
    'JERSEY',
    'JORDAN',
    'KAZAKHSTAN',
    'KENYA',
    'KIRIBATI',
    "KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)",
    'KOREA (THE REPUBLIC OF)',
    'KUWAIT',
    'KYRGYZSTAN',
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
    'LATVIA',
    'LEBANON',
    'LESOTHO',
    'LIBERIA',
    'LIBYA',
    'LIECHTENSTEIN',
    'LITHUANIA',
    'LUXEMBOURG',
    'MACAO',
    'MADAGASCAR',
    'MALAWI',
    'MALAYSIA',
    'MALDIVES',
    'MALI',
    'MARSHALL ISLANDS (THE)',
    'MARTINIQUE',
    'MAURITANIA',
    'MAURITIUS',
    'MAYOTTE',
    'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP',
    'MEXICO',
    'MICRONESIA (FEDERATED STATES OF)',
    'MOLDOVA (THE REPUBLIC OF)',
    'MONACO',
    'MONGOLIA',
    'MONTENEGRO',
    'MONTSERRAT',
    'MOROCCO',
    'MOZAMBIQUE',
    'MYANMAR',
    'NAMIBIA',
    'NAMIBIA',
    'NAURU',
    'NEPAL',
    'NETHERLANDS (THE)',
    'NEW CALEDONIA',
    'NEW ZEALAND',
    'NICARAGUA',
    'NIGER (THE)',
    'NIGERIA',
    'NIUE',
    'NORFOLK ISLAND',
    'NORTHERN MARIANA ISLANDS (THE)',
    'NORWAY',
    'OMAN',
    'PAKISTAN',
    'PALAU',
    'PALESTINE, STATE OF',
    'PANAMA',
    'PANAMA',
    'PAPUA NEW GUINEA',
    'PARAGUAY',
    'PERU',
    'PHILIPPINES (THE)',
    'PITCAIRN',
    'POLAND',
    'PORTUGAL',
    'PUERTO RICO',
    'QATAR',
    'REPUBLIC OF NORTH MACEDONIA',
    'ROMANIA',
    'RUSSIAN FEDERATION (THE)',
    'RWANDA',
    'RÉUNION',
    'SAINT BARTHÉLEMY',
    'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
    'SAINT KITTS AND NEVIS',
    'SAINT LUCIA',
    'SAINT MARTIN (FRENCH PART)',
    'SAINT PIERRE AND MIQUELON',
    'SAINT VINCENT AND THE GRENADINES',
    'SAMOA',
    'SAN MARINO',
    'SAO TOME AND PRINCIPE',
    'SAUDI ARABIA',
    'SENEGAL',
    'SERBIA',
    'SEYCHELLES',
    'SIERRA LEONE',
    'SINGAPORE',
    'SINT MAARTEN (DUTCH PART)',
    'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"',
    'SLOVAKIA',
    'SLOVENIA',
    'SOLOMON ISLANDS',
    'SOMALIA',
    'SOUTH AFRICA',
    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
    'SOUTH SUDAN',
    'SPAIN',
    'SRI LANKA',
    'SUDAN (THE)',
    'SURINAME',
    'SVALBARD AND JAN MAYEN',
    'SWAZILAND',
    'SWEDEN',
    'SWITZERLAND',
    'SYRIAN ARAB REPUBLIC',
    'TAIWAN (PROVINCE OF CHINA)',
    'TAJIKISTAN',
    'TANZANIA, UNITED REPUBLIC OF',
    'THAILAND',
    'TIMOR-LESTE',
    'TOGO',
    'TOKELAU',
    'TONGA',
    'TRINIDAD AND TOBAGO',
    'TUNISIA',
    'TURKEY',
    'TURKMENISTAN',
    'TURKS AND CAICOS ISLANDS (THE)',
    'TUVALU',
    'UGANDA',
    'UKRAINE',
    'UNITED ARAB EMIRATES (THE)',
    'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
    'UNITED STATES MINOR OUTLYING ISLANDS (THE)',
    'UNITED STATES OF AMERICA (THE)',
    'URUGUAY',
    'UZBEKISTAN',
    'VANUATU',
    'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
    'VIET NAM',
    'VIRGIN ISLANDS (BRITISH)',
    'VIRGIN ISLANDS (U.S.)',
    'WALLIS AND FUTUNA',
    'WESTERN SAHARA',
    'YEMEN',
    'ZAMBIA',
    'ZIMBABWE',
    'ÅLAND ISLANDS',
  ];

  var Countrydetails = {
    'Afghanistan': 'AFN',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'American Samoa': 'ASM',
    'Andorra': 'AND',
    'Angola': 'AGO',
    'Anguilla': 'AIA',
    'Antarctica': 'ATA',
    'Antigua and Barbuda': 'ATG',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Aruba': 'ABW',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Bahamas (the)': 'BHS',
    'Bahrain': 'BHR',
    'Bangladesh': 'BDT',
    'Barbados': 'BRB',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Belize': 'BLZ',
    'Benin': 'BEN',
    'Bermuda': 'BMU',
    'Bhutan': 'BTN',
    'Bolivia (Plurinational State of)': 'BOL',
    'Bonaire, Sint Eustatius and Saba': 'BES',
    'Bosnia and Herzegovina': 'BIH',
    'Botswana': 'BWA',
    'Bouvet Island': 'BVT',
    'Brazil': 'BRA',
    'British Indian Ocean Territory (the)': 'IOT',
    'Brunei Darussalam': 'BRN',
    'Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'Burundi': 'BDI',
    'Cabo Verde': 'CPV',
    'Cambodia': 'KHM',
    'Cameroon': 'CMR',
    'Canada': 'CAN',
    'Cayman Islands (the)': 'CYM',
    'Central African Republic (the)': 'CAF',
    'Chad': 'TCD',
    'Chile': 'CHL',
    'China': 'CHN',
    'Christmas Island': 'CXR',
    'Cocos (Keeling) Islands (the)': 'CCK',
    'Colombia': 'COL',
    'Comoros (the)': 'COM',
    'Congo (the Democratic Republic of the)': 'COD',
    'Congo (the)': 'COG',
    'Cook Islands (the)': 'COK',
    'Costa Rica': 'CRI',
    'Croatia': 'HRV',
    'Cuba': 'CUB',
    'Curaçao': 'CUW',
    'Cyprus': 'CYP',
    'Czechia': 'CZE',
    "Côte d'Ivoire": 'CIV',
    'Denmark': 'DNK',
    'Djibouti': 'DJI',
    'Dominica': 'DMA',
    'Dominican Republic (the)': 'DOM',
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'El Salvador': 'SLV',
    'Equatorial Guinea': 'GNQ',
    'Eritrea': 'ERI',
    'Estonia': 'EST',
    'Eswatini': 'SWZ',
    'Ethiopia': 'ETH',
    'Falkland Islands (the) [Malvinas]': 'FLK',
    'Faroe Islands (the)': 'FRO',
    'Fiji': 'FJI',
    'Finland': 'FIN',
    'France': 'FRA',
    'French Guiana': 'GUF',
    'French Polynesia': 'PYF',
    'French Southern Territories (the)': 'ATF',
    'Gabon': 'GAB',
    'Gambia (the)': 'GMB',
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Ghana': 'GHA',
    'Gibraltar': 'GIB',
    'Greece': 'GRC',
    'Greenland': 'GRL',
    'Grenada': 'GRD',
    'Guadeloupe': 'GLP',
    'Guam': 'GUM',
    'Guatemala': 'GTM',
    'Guernsey': 'GGY',
    'Guinea': 'GIN',
    'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY',
    'Haiti': 'HTI',
    'Heard Island and McDonald Islands': 'HMD',
    'Holy See (the)': 'VAT',
    'Honduras': 'HND',
    'Hong Kong': 'HKG',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'India': 'INR',
    'Indonesia': 'IDN',
    'Iran (Islamic Republic of)': 'IRN',
    'Iraq': 'IRQ',
    'Ireland': 'IRL',
    'Isle of Man': 'IMN',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'Jersey': 'JEY',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kiribati': 'KIR',
    "Korea (the Democratic People's Republic of)": 'PRK',
    'Korea (the Republic of)': 'KOR',
    'Kuwait': 'KWT',
    'Kyrgyzstan': 'KGZ',
    "Lao People's Democratic Republic (the)": 'LAO',
    'Latvia': 'LVA',
    'Lebanon': 'LBN',
    'Lesotho': 'LSO',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Macao': 'MAC',
    'Madagascar': 'MDG',
    'Malawi': 'MWI',
    'Malaysia': 'MYS',
    'Maldives': 'MDV',
    'Mali': 'MLI',
    'Malta': 'MLT',
    'Marshall Islands (the)': 'MHL',
    'Martinique': 'MTQ',
    'Mauritania': 'MRT',
    'Mauritius': 'MUS',
    'Mayotte': 'MYT',
    'Mexico': 'MEX',
    'Micronesia (Federated States of)': 'FSM',
    'Moldova (the Republic of)': 'MDA',
    'Monaco': 'MCO',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Montserrat': 'MSR',
    'Morocco': 'MAR',
    'Mozambique': 'MOZ',
    'Myanmar': 'MMR',
    'Namibia': 'NAM',
    'Nauru': 'NRU',
    'Nepal': 'NPL',
    'Netherlands (the)': 'NLD',
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'Nicaragua': 'NIC',
    'Niger (the)': 'NER',
    'Nigeria': 'NGA',
    'Niue': 'NIU',
    'Norfolk Island': 'NFK',
    'Northern Mariana Islands (the)': 'MNP',
    'Norway': 'NOR',
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Palau': 'PLW',
    'Palestine, State of': 'PSE',
    'Panama': 'PAN',
    'Papua New Guinea': 'PNG',
    'Paraguay': 'PRY',
    'Peru': 'PER',
    'Philippines (the)': 'PHL',
    'Pitcairn': 'PCN',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Puerto Rico': 'PRI',
    'Qatar': 'QAT',
    'Republic of North Macedonia': 'MKD',
    'Romania': 'ROU',
    'Russian Federation (the)': 'RUS',
    'Rwanda': 'RWA',
    'Réunion': 'REU',
    'Saint Barthélemy': 'BLM',
    'Saint Helena, Ascension and Tristan da Cunha': 'SHN',
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'Saint Martin (French part)': 'MAF',
    'Saint Pierre and Miquelon': 'SPM',
    'Saint Vincent and the Grenadines': 'VCT',
    'Samoa': 'WSM',
    'San Marino': 'SMR',
    'Sao Tome and Principe': 'STP',
    'Saudi Arabia': 'SAU',
    'Senegal': 'SEN',
    'Serbia': 'SRB',
    'Seychelles': 'SYC',
    'Sierra Leone': 'SLE',
    'Singapore': 'SGP',
    'Sint Maarten (Dutch part)': 'SXM',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Solomon Islands': 'SLB',
    'Somalia': 'SOM',
    'South Africa': 'ZAF',
    'South Georgia and the South Sandwich Islands': 'SGS',
    'South Sudan': 'SSD',
    'Spain': 'ESP',
    'Sri Lanka': 'LKA',
    'Sudan (the)': 'SDN',
    'Suriname': 'SUR',
    'Svalbard and Jan Mayen': 'SJM',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Syrian Arab Republic': 'SYR',
    'Taiwan (Province of China)': 'TWN',
    'Tajikistan': 'TJK',
    'Tanzania, United Republic of': 'TZA',
    'Thailand': 'THA',
    'Timor-Leste': 'TLS',
    'Togo': 'TGO',
    'Tokelau': 'TKL',
    'Tonga': 'TON',
    'Trinidad and Tobago': 'TTO',
    'Tunisia': 'TUN',
    'Turkey': 'TUR',
    'Turkmenistan': 'TKM',
    'Turks and Caicos Islands (the)': 'TCA',
    'Tuvalu': 'TUV',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'United Arab Emirates (the)': 'ARE',
    'United Kingdom of Great Britain and Northern Ireland (the)': 'GBR',
    'United States Minor Outlying Islands (the)': 'UMI',
    'United States of America (the)': 'USD',
    'Uruguay': 'URY',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'Venezuela (Bolivarian Republic of)': 'VEN',
    'Viet Nam': 'VNM',
    'Virgin Islands (British)': 'VGB',
    'Virgin Islands (U.S.)': 'VIR',
    'Wallis and Futuna': 'WLF',
    'Western Sahara': 'ESH',
    'Yemen': 'YEM',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE',
    'Åland Islands': 'ALA',
  };
  var Countrydetails2 = {
    'AFGHANISTAN': 'AFN',
    "ALBANIA": 'ALL',
    'ALGERIA': 'DZD',
    'AMERICAN SAMOA': 'USD',
    'ANDORRA': 'EUR',
    'ANGOLA': 'AOA',
    'ANGUILLA': 'XCD',
    'ANTARCTICA': '',
    'ANTIGUA AND BARBUDA': 'XCD',
    'ARGENTINA': 'ARS',
    'ARMENIA': 'AMD',
    'ARUBA': 'AWG',
    'AUSTRALIA': 'AUD',
    'AUSTRIA': 'EUR',
    'AZERBAIJAN': 'AZN',
    'BAHAMAS (THE)': 'BSD',
    'BAHRAIN': 'BHD',
    'BANGLADESH': 'BDT',
    'BARBADOS': 'BBD',
    'BELARUS': 'BYN',
    'BELGIUM': 'EUR',
    'BELIZE': 'BZD',
    'BENIN': 'XOF',
    'BERMUDA': 'BMD',
    'BHUTAN': 'BTN',
    'BOLIVIA (PLURINATIONAL STATE OF)': 'BOB',
    'BONAIRE, SINT EUSTATIUS AND SABA': 'USD',
    'BOSNIA AND HERZEGOVINA': 'BAM',
    'BOTSWANA': 'BWP',
    'BOUVET ISLAND': 'NOK',
    'BRAZIL': 'BRL',
    'BRITISH INDIAN OCEAN TERRITORY (THE)': 'USD',
    'BRUNEI DARUSSALAM': 'BND',
    'BULGARIA': 'BGN',
    'BURKINA FASO': 'XOF',
    'BURUNDI': 'BIF',
    'CABO VERDE': 'CVE',
    'CAMBODIA': 'KHR',
    'CAMEROON': 'XAF',
    'CANADA': 'CAD',
    'CAYMAN ISLANDS (THE)': 'KYD',
    'CENTRAL AFRICAN REPUBLIC (THE)': 'XAF',
    'CHAD': 'XAF',
    'CHILE': 'CLP',
    'CHINA': 'CNY',
    'CHRISTMAS ISLAND': 'AUD',
    'COCOS (KEELING) ISLANDS (THE)': 'AUD',
    'COLOMBIA': 'COP',
    'COMOROS (THE)': 'KMF',
    'CONGO (THE DEMOCRATIC REPUBLIC OF THE)': 'CDF',
    'CONGO (THE)': 'XAF',
    'COOK ISLANDS (THE)': 'NZD',
    'COSTA RICA': 'CRC',
    'CROATIA': 'EUR',
    'CUBA': 'CUP',
    'CURAÇAO': 'ANG',
    'CYPRUS': 'EUR',
    'CZECH REPUBLIC (THE)': 'CZK',
    "CÔTE D'IVOIRE": 'XOF',
    'DENMARK': 'DKK',
    'DJIBOUTI': 'DJF',
    'DOMINICA': 'XCD',
    'DOMINICAN REPUBLIC (THE)': 'DOP',
    'ECUADOR': 'USD',
    'EGYPT': 'EGP',
    'EL SALVADOR': 'SVC',
    'EQUATORIAL GUINEA': 'XAF',
    'ERITREA': 'ERN',
    'ESTONIA': 'EUR',
    'ETHIOPIA': 'ETB',
    'EUROPEAN UNION': 'EUR',
    'FALKLAND ISLANDS (THE) [MALVINAS]': 'FKP',
    'FAROE ISLANDS (THE)': 'DKK',
    'FIJI': 'FJD',
    'FINLAND': 'EUR',
    'FRANCE': 'EUR',
    'FRENCH GUIANA': 'EUR',
    'FRENCH POLYNESIA': 'XPF',
    'FRENCH SOUTHERN TERRITORIES (THE)': 'EUR',
    'GABON': 'XAF',
    'GAMBIA (THE)': 'GMD',
    'GEORGIA': 'GEL',
    'GERMANY': 'EUR',
    'GHANA': 'GHS',
    'GIBRALTAR': 'GIP',
    'GREECE': 'EUR',
    'GREENLAND': 'DKK',
    'GRENADA': 'XCD',
    'GUADELOUPE': 'EUR',
    'GUAM': 'USD',
    'GUATEMALA': 'GTQ',
    'GUERNSEY': 'GBP',
    'GUINEA': 'GNF',
    'GUINEA-BISSAU': 'XOF',
    'GUYANA': 'GYD',
    'HAITI': 'HTG',
    'HEARD ISLAND AND McDONALD ISLANDS': 'AUD',
    'HOLY SEE (THE)': 'EUR',
    'HONDURAS': 'HNL',
    'HONG KONG': 'HKD',
    'HUNGARY': 'HUF',
    'ICELAND': 'ISK',
    'INDIA': 'INR',
    'INDONESIA': 'IDR',
    'INTERNATIONAL MONETARY FUND (IMF)': 'XDR',
    'IRAN (ISLAMIC REPUBLIC OF)': 'IRR',
    'IRAQ': 'IQD',
    'IRELAND': 'EUR',
    'ISLE OF MAN': 'GBP',
    'ISRAEL': 'ILS',
    'ITALY': 'EUR',
    'JAMAICA': 'JMD',
    'JAPAN': 'JPY',
    'JERSEY': 'GBP',
    'JORDAN': 'JOD',
    'KAZAKHSTAN': 'KZT',
    'KENYA': 'KES',
    'KIRIBATI': 'AUD',
    "KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)": 'KPW',
    'KOREA (THE REPUBLIC OF)': 'KRW',
    'KUWAIT': 'KWD',
    'KYRGYZSTAN': 'KGS',
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)": 'LAK',
    'LATVIA': 'EUR',
    'LEBANON': 'LBP',
    'LESOTHO': 'LSL',
    'LIBERIA': 'LRD',
    'LIBYA': 'LYD',
    'LIECHTENSTEIN': 'CHF',
    'LITHUANIA': 'EUR',
    'LUXEMBOURG': 'EUR',
    'MACAO': 'MOP',
    'MADAGASCAR': 'MGA',
    'MALAWI': 'MWK',
    'MALAYSIA': 'MYR',
    'MALDIVES': 'MVR',
    'MALI': 'XOF',
    'MALTA': 'EUR',
    'MARSHALL ISLANDS (THE)': 'USD',
    'MARTINIQUE': 'EUR',
    'MAURITANIA': 'MRU',
    'MAURITIUS': 'MUR',
    'MAYOTTE': 'EUR',
    'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP': 'XUA',
    'MEXICO': 'MXN',
    'MICRONESIA (FEDERATED STATES OF)': 'USD',
    'MOLDOVA (THE REPUBLIC OF)': 'MDL',
    'MONACO': 'EUR',
    'MONGOLIA': 'MNT',
    'MONTENEGRO': 'EUR',
    'MONTSERRAT': 'XCD',
    'MOROCCO': 'MAD',
    'MOZAMBIQUE': 'MZN',
    'MYANMAR': 'MMK',
    'NAMIBIA': 'NAD',
    'NAURU': 'AUD',
    'NEPAL': 'NPR',
    'NETHERLANDS (THE)': 'EUR',
    'NEW CALEDONIA': 'XPF',
    'NEW ZEALAND': 'NZD',
    'NICARAGUA': 'NIO',
    'NIGER (THE)': 'XOF',
    'NIGERIA': 'NGN',
    'NIUE': 'NZD',
    'NORFOLK ISLAND': 'AUD',
    'NORTHERN MARIANA ISLANDS (THE)': 'USD',
    'NORWAY': 'NOK',
    'OMAN': 'OMR',
    'PAKISTAN': 'PKR',
    'PALAU': 'USD',
    'PALESTINE, STATE OF': '',
    'PANAMA': 'PAB',
    'PAPUA NEW GUINEA': 'PGK',
    'PARAGUAY': 'PYG',
    'PERU': 'PEN',
    'PHILIPPINES (THE)': 'PHP',
    'PITCAIRN': 'NZD',
    'POLAND': 'PLN',
    'PORTUGAL': 'EUR',
    'PUERTO RICO': 'USD',
    'QATAR': 'QAR',
    'REPUBLIC OF NORTH MACEDONIA': 'MKD',
    'ROMANIA': 'RON',
    'RUSSIAN FEDERATION (THE)': 'RUB',
    'RWANDA': 'RWF',
    'RÉUNION': 'EUR',
    'SAINT BARTHÉLEMY': 'EUR',
    'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA': 'SHP',
    'SAINT KITTS AND NEVIS': 'XCD',
    'SAINT LUCIA': 'XCD',
    'SAINT MARTIN (FRENCH PART)': 'EUR',
    'SAINT PIERRE AND MIQUELON': 'EUR',
    'SAINT VINCENT AND THE GRENADINES': 'XCD',
    'SAMOA': 'WST',
    'SAN MARINO': 'EUR',
    'SAO TOME AND PRINCIPE': 'STN',
    'SAUDI ARABIA': 'SAR',
    'SENEGAL': 'XOF',
    'SERBIA': 'RSD',
    'SEYCHELLES': 'SCR',
    'SIERRA LEONE': 'SLE',
    'SINGAPORE': 'SGD',
    'SINT MAARTEN (DUTCH PART)': 'ANG',
    'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"': 'XSU',
    'SLOVAKIA': 'EUR',
    'SLOVENIA': 'EUR',
    'SOLOMON ISLANDS': 'SBD',
    'SOMALIA': 'SOS',
    'SOUTH AFRICA': 'ZAR',
    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'GBP',
    'SOUTH SUDAN': 'SSP',
    'SPAIN': 'EUR',
    'SRI LANKA': 'LKR',
    'SUDAN (THE)': 'SDG',
    'SURINAME': 'SRD',
    'SVALBARD AND JAN MAYEN': 'NOK',
    'SWAZILAND': 'SZL',
    'SWEDEN': 'SEK',
    'SWITZERLAND': 'CHF',
    'SYRIAN ARAB REPUBLIC': 'SYP',
    'TAIWAN (PROVINCE OF CHINA)': 'TWD',
    'TAJIKISTAN': 'TJS',
    'TANZANIA, UNITED REPUBLIC OF': 'TZS',
    'THAILAND': 'THB',
    'TIMOR-LESTE': 'USD',
    'TOGO': 'XOF',
    'TOKELAU': 'NZD',
    'TONGA': 'TOP',
    'TRINIDAD AND TOBAGO': 'TTD',
    'TUNISIA': 'TND',
    'TURKEY': 'TRY',
    'TURKMENISTAN': 'TMT',
    'TURKS AND CAICOS ISLANDS (THE)': 'USD',
    'TUVALU': 'AUD',
    'UGANDA': 'UGX',
    'UKRAINE': 'UAH',
    'UNITED ARAB EMIRATES (THE)': 'AED',
    'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)': 'GBP',
    'UNITED STATES MINOR OUTLYING ISLANDS (THE)': 'USD',
    'UNITED STATES OF AMERICA (THE)': 'USD',
    'URUGUAY': 'UYU',
    'UZBEKISTAN': 'UZS',
    'VANUATU': 'VUV',
    'VENEZUELA (BOLIVARIAN REPUBLIC OF)': 'VEF',
    'VIET NAM': 'VND',
    'VIRGIN ISLANDS (BRITISH)': 'USD',
    'VIRGIN ISLANDS (U.S.)': 'USD',
    'WALLIS AND FUTUNA': 'XPF',
    'WESTERN SAHARA': 'MAD',
    'YEMEN': 'YER',
    'ZAMBIA': 'ZMW',
    'ZIMBABWE': 'ZWL',
    'ÅLAND ISLANDS': 'EUR',
  };
  final List<String> countryCodes = [
    'af',
    'al',
    'dz',
    'as',
    'ad',
    'ao',
    'ai',
    'aq',
    'ag',
    'ar',
    'am',
    'aw',
    'au',
    'at',
    'az',
    'bs',
    'bh',
    'bd',
    'bb',
    'by',
    'be',
    'bz',
    'bj',
    'bm',
    'bt',
    'bo',
    'bq',
    'ba',
    'bw',
    'bv',
    'br',
    'io',
    'bn',
    'bg',
    'bf',
    'bi',
    'cv',
    'kh',
    'cm',
    'ca',
    'ky',
    'cf',
    'td',
    'cl',
    'cn',
    'cx',
    'cc',
    'co',
    'km',
    'cd',
    'cg',
    'ck',
    'cr',
    'hr',
    'cu',
    'cw',
    'cy',
    'cz',
    'ci',
    'dk',
    'dj',
    'dm',
    'do',
    'ec',
    'eg',
    'sv',
    'gq',
    'er',
    'ee',
    'sz',
    'et',
    'fk',
    'fo',
    'fj',
    'fi',
    'fr',
    'gf',
    'pf',
    'tf',
    'ga',
    'gm',
    'ge',
    'de',
    'gh',
    'gi',
    'gr',
    'gl',
    'gd',
    'gp',
    'gu',
    'gt',
    'gg',
    'gn',
    'gw',
    'gy',
    'ht',
    'hm',
    'va',
    'hn',
    'hk',
    'hu',
    'is',
    'in',
    'id',
    'ir',
    'iq',
    'ie',
    'im',
    'il',
    'it',
    'jm',
    'jp',
    'je',
    'jo',
    'kz',
    'ke',
    'ki',
    'kp',
    'kr',
    'kw',
    'kg',
    'la',
    'lv',
    'lb',
    'ls',
    'lr',
    'ly',
    'li',
    'lt',
    'lu',
    'mo',
    'mg',
    'mw',
    'my',
    'mv',
    'ml',
    'mt',
    'mh',
    'mq',
    'mr',
    'mu',
    'yt',
    'mx',
    'fm',
    'md',
    'mc',
    'mn',
    'me',
    'ms',
    'ma',
    'mz',
    'mm',
    'na',
    'nr',
    'np',
    'nl',
    'nc',
    'nz',
    'ni',
    'ne',
    'ng',
    'nu',
    'nf',
    'mp',
    'no',
    'om',
    'pk',
    'pw',
    'ps',
    'pa',
    'pg',
    'py',
    'pe',
    'ph',
    'pn',
    'pl',
    'pt',
    'pr',
    'qa',
    'mk',
    'ro',
    'ru',
    'rw',
    're',
    'bl',
    'sh',
    'kn',
    'lc',
    'mf',
    'pm',
    'vc',
    'ws',
    'sm',
    'st',
    'sa',
    'sn',
    'rs',
    'sc',
    'sl',
    'sg',
    'sx',
    'sk',
    'si',
    'sb',
    'so',
    'za',
    'gs',
    'ss',
    'es',
    'lk',
    'sd',
    'sr',
    'sj',
    'se',
    'ch',
    'sy',
    'tw',
    'tj',
    'tz',
    'th',
    'tl',
    'tg',
    'tk',
    'to',
    'tt',
    'tn',
    'tr',
    'tm',
    'tc',
    'tv',
    'ug',
    'ua',
    'ae',
    'gb',
    'um',
    'us',
    'uy',
    'uz',
    'vu',
    've',
    'vn',
    'vg',
    'vi',
    'wf',
    'eh',
    'ye',
    'zm',
    'zw',
    'ax',
  ];
}
